FROM node:24-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN corepack enable && pnpm install --frozen-lockfile

COPY . .

EXPOSE 80

CMD ["pnpm", "dev", "--hostname", "0.0.0.0", "-p", "80"]
